Capstone implementation
nelsinofrancisco/capstone1 pull request #1
Opened 2021-08-06 17:05 UTC by nelsinofrancisco

# Capstone Project

# Features Added:

- Home Page (Mobile and Desk Versions)
- About Page (Mobile and Desk Versions)
- Js to handle the creation of the film section and to add some functionalities for menu's or showing the full content of the page

2021-08-06 18:13 UTC, MahmoudBakr23 requested changes
Hello @nelsinofrancisco 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

- Linter is correct
- Great use of ES6 features
- Nice follow to the given design
- Great semantic HTML usage

There are some excellent points that you have made perfectly. Keep up! 💪

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is to improve the code you wrote and not criticize it. 😄

 ## Required Changes ♻️

- [ ] In the PR, please write a more descriptive PR headline instead of the default (branch name) one!
- [ ] Kindly fix the broken screenshot of the app in your README file.
- [ ] Please fix the broken MIT link in your README file.
- [ ] Please provide a valid live demo link for your app in the README file.
- [ ] Kindly fill the empty sections such as setting up and installing the project locally.
- [ ] Please make sure to give credit to the design's author on your README file. Kindly see more details [here](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=Original%20design%20idea,of%20your%20project.).
Please note that such small mistakes regarding the professionalism of the project's repo might leave a bad impression on future viewers. 🙏

- [ ] I cannot see the short presentation video attached to the PR summary. Please do so as required in this project.

_Also, the README file wasn't loaded for inline comments._

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-06 18:13 UTC, MahmoudBakr23 commented on scripts/main.js
> +const seeMoreDiv = document.getElementById('see-more-mob');
- [ ] Please note that this 'See More' button is for just the 'Featured Films' section. If you think about it, you'll find that it makes more sense that way. The button's action is to show the rest of the featured films. However, if the button isn't triggered, it's supposed to still see the 'Partners' section and the footer 😄

_Note: I know that you managed to do it this way because of the design template, but the design's idea is to show off the website's main sections, and the rest is predictable so it's not shown exactly._

2021-08-06 18:13 UTC, MahmoudBakr23 commented on index.html
> +    </footer>
- [ ] According to the project requirements. Please make sure to style the footer's background to be dark in the Desktop version at both home and about pages.

2021-08-06 18:13 UTC, MahmoudBakr23 commented on index.html
> +        <h1 class="headline-desk-size headline-title default-family fw-900 fc-orange fs-48 mb-2">
- [ ] Before this heading, you missed the first smaller line of text. Kindly add it to match the design template and the project requirements. 🙏

_Take a look at the following images to compare._
**[ORIGINAL DESIGN](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)**
![Screenshot](https://user-images.githubusercontent.com/47625407/128551625-c2caa603-53e1-40e3-b0b1-8cc994f268f6.png)
**YOUR DESIGN**
![Screenshot1](https://user-images.githubusercontent.com/47625407/128551690-fe81a3ad-5930-4a83-b22b-36d040384ffe.png)

2021-08-06 18:13 UTC, MahmoudBakr23 commented on index.html
> +        <div id="programs-out-container" class="programs-out-container d-flex d-column d-align-center">
- [ ] For the programs section, kindly make sure that each section should have an image, title, and description, and a line of text at the bottom. 🙏

_Take a look at the following image from the original design and compare it to yours.._
**[ORIGINAL DESIGN](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)**
![Screenshot](https://user-images.githubusercontent.com/47625407/128552188-1d149757-77ca-45ac-aa42-ed144439fb16.png)

2021-08-06 18:13 UTC, MahmoudBakr23 commented on index.html
> +
- [ ] Kindly delete this blank line 👍 Please keep in mind that we're only adding blank lines for a reason such as separating two sections or two large pieces of code apart from each other for readability. 🙏 

_You can read about this tip and more on this [link](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md#:~:text=Do%20not%20add%20blank%20lines%2C%20spaces%2C%20or%20indentations%20without%20a%20reason.)._
_Please apply this request to all similar situations through the pages._

2021-08-06 18:13 UTC, MahmoudBakr23 commented on about.html
> +      </h2>
- [ ] At the end of this section on the about page, there should be another text that refers to an email or other social connection method as described in the project requirements and the design template. Please let's add that 🙏 

_Take a look at the original design and compare it to yours._
![Screenshot](https://user-images.githubusercontent.com/47625407/128554140-33f95e35-eaa0-41c1-9af8-a08469db7fe5.png)

2021-08-06 18:22 UTC, nelsinofrancisco commented on index.html
> +    </footer>
Mahmoud could you please explain why do you require this change? The footer is not dark in the template! 
![image](https://user-images.githubusercontent.com/85680436/128555192-bdf5e8ec-8fa9-49fa-b635-1599c5617f4f.png)

2021-08-06 18:23 UTC, nelsinofrancisco commented on index.html
> +        <div id="programs-out-container" class="programs-out-container d-flex d-column d-align-center">
In this one my images are self-explanatory I don't think I need to display a title and an image if the image describes herself you know? Could you reconsider this?

2021-08-06 18:24 UTC, nelsinofrancisco commented on index.html
> +        <h1 class="headline-desk-size headline-title default-family fw-900 fc-orange fs-48 mb-2">
Ok I didn't missed this one I choose to not add a small title but ok I can do it

2021-08-06 21:29 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑🛑🛠🛠**
Hello @nelsinofrancisco 👋🏽
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.
## Required Changes ♻️
_Check the comments under the review._👇🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-06 21:29 UTC, emmanuellekamwa commented on index.html
> +    </footer>
As said by the previous code reviewer the background color of the footer should be dark on desktop view and white on mobile view. Please kindly fix that

2021-08-07 01:03 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @nelsinofrancisco  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

![doing good](https://user-images.githubusercontent.com/60631456/128583075-08597448-be83-4f7f-8d34-d53093aa692d.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-07 01:21 UTC, merged